### ISSUE TITLE
`AttributeError: module 'typing' has no attribute 'Literal'`

### ISSUE THREAD

**Issue by samwaseda** [pyscioffice/pyauthenticator#50]
When I installed `pyauthenticator` and executed it, I got the following message

```python
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pyauthenticator", line 6, in <module>
    from pyauthenticator.__main__ import command_line_parser
  File "/opt/anaconda3/lib/python3.7/site-packages/pyauthenticator/__init__.py", line 4, in <module>
    from pyauthenticator.share import (
  File "/opt/anaconda3/lib/python3.7/site-packages/pyauthenticator/share.py", line 7, in <module>
    import otpauth
  File "/opt/anaconda3/lib/python3.7/site-packages/otpauth/__init__.py", line 1, in <module>
    from .core import SupportedAlgorithms
  File "/opt/anaconda3/lib/python3.7/site-packages/otpauth/core.py", line 6, in <module>
    SupportedAlgorithms = t.Literal["SHA1", "SHA256", "SHA512"]
AttributeError: module 'typing' has no attribute 'Literal'
```

**Comment by jan-janssen** [comment]
This error is typically related to an outdated `pyauthenticator` version, maybe `0.0.7`? Try using the more up to date version `0.2.0`. The version `0.2.0` requires Python `>=3.8` so if you are still using `3.7` this might be a reason why the old `pyauthenticator` version was installed. Unfortunately, the old version is broken.
